robot_ip: "192.168.11.4"
camera_ids:
  front: "145522067924"
  hand: "153122070885"
# gelsight_ids:
#   tactile_left: "GelSight Mini R0B 2BNK-CE0U: Ge"
#   tactile_right: "GelSight Mini R0B 2BG8-0H3X: Ge"
